{
  perSystem = psArgs: {
    text.readme = {
      order = [
        "intro"
        "home-manager"
        "nixos"
        "nixvim"
        "contributing"
      ];

      parts.intro =
        # markdown
        ''
          # nix-configs

          <!-- Generated by `nix run .#write-files`. Edit `modules/docs/`, not this file. -->

          My NixOS, Home Manager and Nixvim configuration.

          It follows [the dendritic pattern](https://github.com/mightyiam/dendritic): every `.nix` file under
          `modules/` is a [flake-parts](https://flake.parts) module, auto-imported by
          [import-tree](https://github.com/vic/import-tree). Nothing is registered by hand - `flake.nix` itself
          is generated by [flake-file](https://github.com/vic/flake-file).

          Modules are composed through four option trees:

          | Option | Holds |
          | --- | --- |
          | `nixos.modules.<name>` | NixOS modules |
          | `home.modules.<name>` | Home Manager modules |
          | `home.user-modules.<user>.<name>` | per-user Home Manager modules |
          | `nixvim.user-modules.<user>.<name>` | per-user Nixvim modules |

        '';
    };

    files.file."README.md".text = psArgs.config.text.readme;
  };
}
